-- Create the social_posts table (if it doesn't verify existence mainly)
create table if not exists social_posts (
  id bigint generated by default as identity primary key,
  platform text not null,
  title text,
  content text,
  image_url text,
  url text,
  likes text,
  comments text,
  published_at timestamp with time zone default timezone('utc'::text, now()),
  language text default 'en'
);

-- Enable RLS
alter table social_posts enable row level security;

-- 1. CLEANUP: Remove old policies to avoid conflicts
drop policy if exists "Public Social Posts are viewable by everyone" on social_posts;
drop policy if exists "Enable insert for anon users" on social_posts;

-- 2. READ ACCESS (Public)
create policy "Public Social Posts are viewable by everyone"
  on social_posts for select
  using ( true );

-- 3. WRITE ACCESS (Public/Anon - Needed for Seeding)
-- WARNING: In production, you might want to restrict this to authenticated users only.
create policy "Enable insert for everyone"
  on social_posts for insert
  with check ( true );
