-- Create the social_posts table
create table if not exists social_posts (
  id bigint generated by default as identity primary key,
  platform text not null, -- 'instagram', 'youtube', 'tiktok', 'facebook'
  title text,
  content text,
  image_url text,
  url text,
  likes text,
  comments text,
  published_at timestamp with time zone default timezone('utc'::text, now()),
  language text default 'en' -- 'en', 'ru', 'lt'
);

-- Enable Row Level Security (RLS)
alter table social_posts enable row level security;

-- Policy: Public Read Access
create policy "Public Social Posts are viewable by everyone"
  on social_posts for select
  using ( true );

-- Policy: Admin Write Access (You can refine this later, for now relying on Service Role usage in scripts)
-- create policy "Admins can insert" on social_posts for insert with check ( auth.role() = 'service_role' );
